stages:
  - deploy

deploy_n8n:
  stage: deploy
  script:
    - echo "Pulling latest image..."
    - docker-compose pull
    - echo "Deploying n8n..."
    - docker-compose up -d --remove-orphans
  only:
    - main
  environment:
    name: production
    url: https://n8n-env.sophosic.ai
    external_url: https://n8n-env.sophosic.ai
