variables:
  DOCKER_REGISTRY: $CI_REGISTRY
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE
  DOCKER_TAG: $CI_COMMIT_SHA
  N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
  N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD}
  N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
  N8N_HOST: "n8n.sophosic.ai"
  N8N_PROTOCOL: "https"
  N8N_PORT: "5678"

stages:
  - build
  - deploy

build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
    - docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:latest
  only:
    - main
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "schedule"
  tags:
    - docker

deploy:
  stage: deploy
  image: alpine:3.16
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh $DEPLOY_USER@$DEPLOY_HOST "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh $DEPLOY_USER@$DEPLOY_HOST "docker pull $DOCKER_IMAGE:$DOCKER_TAG"
    - ssh $DEPLOY_USER@$DEPLOY_HOST "docker stop n8n || true"
    - ssh $DEPLOY_USER@$DEPLOY_HOST "docker rm n8n || true"
    - ssh $DEPLOY_USER@$DEPLOY_HOST "docker run -d --name n8n --restart unless-stopped -p 5678:5678
      -e N8N_BASIC_AUTH_ACTIVE=true
      -e N8N_BASIC_AUTH_USER=$N8N_BASIC_AUTH_USER
      -e N8N_BASIC_AUTH_PASSWORD=$N8N_BASIC_AUTH_PASSWORD
      -e N8N_ENCRYPTION_KEY=$N8N_ENCRYPTION_KEY
      -e N8N_HOST=$N8N_HOST
      -e N8N_PROTOCOL=$N8N_PROTOCOL
      -e N8N_PORT=$N8N_PORT
      -v n8n_data:/home/node/.n8n
      $DOCKER_IMAGE:$DOCKER_TAG"
  only:
    - main
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "schedule"
  environment:
    name: production
    url: https://n8n.sophosic.ai
  tags:
    - docker

# Schedule pipeline to run every day at 2 AM UTC
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_BRANCH == "main"
